In [1]:
import numpy as np
from sympy import *

# Теор. подсчёт

In [2]:
p = np.pi

In [3]:
A = np.array([[0, 1, 4 - 8/p, 4/p, 4/p],
              [1, 0,       1,   1,   1],
              [4 - 8/p, 1, 0, 4/p, 4/p],
              [4/p, 1, 4/p, 0, 4 - 8/p],
              [4/p, 1, 4/p, 4 - 8/p, 0]])

In [4]:
Matrix(A)

Matrix([
[               0, 1.0, 1.45352091052967, 1.27323954473516, 1.27323954473516],
[             1.0,   0,              1.0,              1.0,              1.0],
[1.45352091052967, 1.0,                0, 1.27323954473516, 1.27323954473516],
[1.27323954473516, 1.0, 1.27323954473516,                0, 1.45352091052967],
[1.27323954473516, 1.0, 1.27323954473516, 1.45352091052967,                0]])

In [5]:
Kb = np.linalg.inv(A)
Matrix(Kb)

Matrix([
[-0.572729322130857, 0.25,  0.115255276340171,  0.228737022895343,  0.228737022895343],
[              0.25, -1.0,               0.25,               0.25,               0.25],
[ 0.115255276340171, 0.25, -0.572729322130856,  0.228737022895343,  0.228737022895343],
[ 0.228737022895343, 0.25,  0.228737022895343, -0.572729322130856,  0.115255276340171],
[ 0.228737022895343, 0.25,  0.228737022895343,  0.115255276340171, -0.572729322130857]])

In [6]:
Kb_dx = Kb.sum(axis=0)
Matrix(Kb_dx)

Matrix([
[0.25],
[   0],
[0.25],
[0.25],
[0.25]])

In [7]:
Kb_dd = Kb.sum()
Kb_dd

1.0000000000000004

In [8]:
H_inf = Kb_dx / Kb_dd
Matrix(H_inf)

Matrix([
[0.25],
[   0],
[0.25],
[0.25],
[0.25]])

In [9]:
Pb = Kb - Kb.sum(axis=1) @ Kb.sum(axis=0) / Kb_dd + np.eye(5)
Matrix(Pb)

Matrix([
[   0.177270677869144, 1.11022302462516e-16,   -0.134744723659829,   -0.021262977104657,   -0.021262977104657],
[1.11022302462516e-16,                -0.25, 1.11022302462516e-16, 8.32667268468867e-17, 2.22044604925031e-16],
[  -0.134744723659829, 1.11022302462516e-16,    0.177270677869144,   -0.021262977104657,   -0.021262977104657],
[  -0.021262977104657, 1.11022302462516e-16,   -0.021262977104657,    0.177270677869144,   -0.134744723659829],
[  -0.021262977104657, 1.11022302462516e-16,   -0.021262977104657,   -0.134744723659829,    0.177270677869144]])

In [10]:
1 + (1!=1)

1

In [11]:
Kb.sum(axis=1)

array([2.50000000e-01, 1.11022302e-16, 2.50000000e-01, 2.50000000e-01,
       2.50000000e-01])

In [12]:
def P_b(x,y):
    d = {'-1': 0, '0': 1, '1':2, 'i': 3, '-i': 4}
    i, j = d[x], d[y]
    return Kb[i,j] - Kb[i,:].sum() * Kb[:,j].sum() / Kb_dd + (i == j)

In [13]:
Pb = np.empty((5,5))
B = ['-1', '0', '1', 'i', '-i']
for i in range(5):
    x = B[i]
    for j in range(5):
        y = B[j]
        Pb[i,j] = P_b(x,y)
Matrix(Pb)

Matrix([
[ 0.364770677869144, 0.25, 0.0527552763401708,  0.166237022895343,  0.166237022895343],
[              0.25,    0,               0.25,               0.25,               0.25],
[0.0527552763401707, 0.25,  0.364770677869144,  0.166237022895343,  0.166237022895343],
[ 0.166237022895343, 0.25,  0.166237022895343,  0.364770677869144, 0.0527552763401707],
[ 0.166237022895343, 0.25,  0.166237022895343, 0.0527552763401708,  0.364770677869143]])

In [14]:
Pb

array([[0.36477068, 0.25      , 0.05275528, 0.16623702, 0.16623702],
       [0.25      , 0.        , 0.25      , 0.25      , 0.25      ],
       [0.05275528, 0.25      , 0.36477068, 0.16623702, 0.16623702],
       [0.16623702, 0.25      , 0.16623702, 0.36477068, 0.05275528],
       [0.16623702, 0.25      , 0.16623702, 0.05275528, 0.36477068]])

In [15]:
P1 = 0.25 * 1/(1-Pb[0,0])
P1

0.3935586587240384

In [16]:
P2 = 0.25 * 1/(1 - Pb[0,0] - Pb[0,2]) + 0.5 * 1/(1 - Pb[0,0] - Pb[0,3]) - 3 * P1
P2

0.314643283184469

In [17]:
P = (Pb[[0,2,3,4]])[:,[0,2,3,4]]

In [18]:
Matrix(P)

Matrix([
[ 0.364770677869144, 0.0527552763401708,  0.166237022895343,  0.166237022895343],
[0.0527552763401707,  0.364770677869144,  0.166237022895343,  0.166237022895343],
[ 0.166237022895343,  0.166237022895343,  0.364770677869144, 0.0527552763401707],
[ 0.166237022895343,  0.166237022895343, 0.0527552763401708,  0.364770677869143]])

In [20]:
x = np.array(P[1])
P[1] = P[3]
P[3] = x
x = np.array(P[:,1]) 
P[:,1] = P[:,3]
P[:,3] = x
P = P / 0.75
P

array([[0.4863609 , 0.22164936, 0.22164936, 0.07034037],
       [0.22164936, 0.4863609 , 0.07034037, 0.22164936],
       [0.22164936, 0.07034037, 0.4863609 , 0.22164936],
       [0.07034037, 0.22164936, 0.22164936, 0.4863609 ]])

In [21]:
np.linalg.solve(,[0,0,0,0])

SyntaxError: invalid syntax (3566482886.py, line 1)

In [22]:
np.linalg.matrix_rank(P.T - np.eye(4))

3

In [24]:
P_calc = (P-np.eye(4)).copy()

In [25]:
for i in [1,2,3]:
    P_calc[i] = P_calc[i] - P_calc[0] * P_calc[i,0] / P_calc[0,0]
P_calc[0] /= P_calc[0,0]
Matrix(P_calc)

Matrix([
[1.0, -0.431527439229755, -0.431527439229755,  -0.13694512154049],
[  0, -0.417991313780868,  0.165988150847168,    0.2520031629337],
[  0,  0.165988150847168, -0.417991313780868,    0.2520031629337],
[  0,    0.2520031629337,    0.2520031629337, -0.504006325867399]])

In [26]:
for i in [0,2,3]:
    P_calc[i] = P_calc[i] - P_calc[1] * P_calc[i,1] / P_calc[1,1]
P_calc[1] /= P_calc[1,1]
Matrix(P_calc)

Matrix([
[1.0,   0, -0.602890908555608, -0.397109091444392],
[  0, 1.0, -0.397109091444392, -0.602890908555608],
[  0,   0, -0.352075910007414,  0.352075910007414],
[  0,   0,  0.352075910007415, -0.352075910007414]])

In [27]:
for i in [0,1,3]:
    P_calc[i] = P_calc[i] - P_calc[2] * P_calc[i,2] / P_calc[2,2]
P_calc[2] /= P_calc[2,2]
Matrix(P_calc)

Matrix([
[1.0,   0,                    0,                 -1.0],
[  0, 1.0, 5.55111512312578e-17,                 -1.0],
[  0,   0,                  1.0,                 -1.0],
[  0,   0,                    0, 6.66133814775094e-16]])

In [28]:
0.75 ** 2

0.5625

In [33]:
P3 = 0.75 / (1 - 0.5625) - 3* P1 - 2 * P2
P3

-0.09567682825533885

In [35]:
2 * (0.25 + 0.25 * (0.365 + 0.166+0.166) / (1 - 0.5625) + 0.5 + 0.5 * (0.365+0.166+0.053) / (1 - 0.5625)) - 6 * P1 - P2

0.9554333358998726

In [20]:
0.366 + 0.166 + 0.053

0.5850000000000001

In [111]:
p0 = np.array([0,1,0,0])
for i in range(20):
    p0 = p0 @ P
p0

array([0.25      , 0.25000001, 0.24999999, 0.25      ])

In [26]:
Px = P / 0.75

In [31]:
np.linalg.matrix_power(Px,5)

array([[0.25623549, 0.24377389, 0.24999531, 0.24999531],
       [0.24377389, 0.25623549, 0.24999531, 0.24999531],
       [0.24999531, 0.24999531, 0.25623549, 0.24377389],
       [0.24999531, 0.24999531, 0.24377389, 0.25623549]])

In [115]:
P4 = 1 - P1 - P2 - P3

In [116]:
P4

0.07283160316236248

# Теор. расчёт N=3 через матрицу

In [36]:
Pb

array([[0.36477068, 0.25      , 0.05275528, 0.16623702, 0.16623702],
       [0.25      , 0.        , 0.25      , 0.25      , 0.25      ],
       [0.05275528, 0.25      , 0.36477068, 0.16623702, 0.16623702],
       [0.16623702, 0.25      , 0.16623702, 0.36477068, 0.05275528],
       [0.16623702, 0.25      , 0.16623702, 0.05275528, 0.36477068]])

In [38]:
P_real = Pb.copy()
P_real[1] = [0,1,0,0,0]
P_real

array([[0.36477068, 0.25      , 0.05275528, 0.16623702, 0.16623702],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.05275528, 0.25      , 0.36477068, 0.16623702, 0.16623702],
       [0.16623702, 0.25      , 0.16623702, 0.36477068, 0.05275528],
       [0.16623702, 0.25      , 0.16623702, 0.05275528, 0.36477068]])

In [39]:
np.linalg.matrix_power(P_real, 10)

array([[0.01408275, 0.94368649, 0.01407401, 0.01407838, 0.01407838],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.01407401, 0.94368649, 0.01408275, 0.01407838, 0.01407838],
       [0.01407838, 0.94368649, 0.01407838, 0.01408275, 0.01407401],
       [0.01407838, 0.94368649, 0.01407838, 0.01407401, 0.01408275]])

In [43]:
H0 = np.array([0.25, 0, 0,0.25, 0.25])
P_real[:,2] = 0

In [45]:
H0 @ np.linalg.matrix_power(P_real, 10)

array([0.00272352, 0.49527812, 0.        , 0.00215398, 0.00215398])

In [89]:
P_real = Pb.copy()
P_real[1] = [0,1,0,0,0]
H0 = np.array([0.25, 0, 0.25,0.25, 0.25])
P_real[:,3] = 0
P_real[3] = 0
H0[3] = 0
H0 @ np.linalg.matrix_power(P_real, 10)

array([0.00215398, 0.49527812, 0.00215398, 0.        , 0.00272352])

In [70]:
Matrix(np.linalg.matrix_power(P_real, 20))

Matrix([
[2.50693868341306e-5, 0.636564816230011, 2.50693103589275e-5, 0, 3.16979981646117e-5],
[                  0,               1.0,                   0, 0,                   0],
[2.50693103589275e-5, 0.636564816230011, 2.50693868341306e-5, 0, 3.16979981646117e-5],
[                  0,                 0,                   0, 0,                   0],
[3.16979981646117e-5, 0.726690968036593, 3.16979981646117e-5, 0, 4.00793456510306e-5]])

In [77]:
P_real

array([[0.36477068, 0.25      , 0.05275528, 0.        , 0.16623702],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.05275528, 0.25      , 0.36477068, 0.        , 0.16623702],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.16623702, 0.25      , 0.16623702, 0.        , 0.36477068]])

In [75]:
P_real

array([[1.        , 0.        , 0.        , 0.        , 0.39814776],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.39814776],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.23239688]])

In [90]:
P_calc = P_real - np.eye(5)
for i in [2, 4]:
    P_calc[i] = P_calc[i] - P_calc[0] * P_calc[i,0] / P_calc[0,0]
P_calc[0] /= P_calc[0,0]
Matrix(P_calc)

Matrix([
[1.0, -0.393558658724038, -0.0830491831882145,    0, -0.261696079043874],
[  0,                  0,                   0,    0,                  0],
[  0,  0.270762295797054,  -0.630848039521937,    0,  0.180042871862442],
[  0,                  0,                   0, -1.0,                  0],
[  0,  0.315424019760968,   0.180042871862442,    0, -0.591725745047219]])

In [91]:
for i in [0,4]:
    P_calc[i] = P_calc[i] - P_calc[2] * P_calc[i,1] / P_calc[2,1]
P_calc[2] /= P_calc[2,1]
Matrix(P_calc)

Matrix([
[1.0,   0,              -1.0,    0,                 0],
[  0,   0,                 0,    0,                 0],
[  0, 1.0, -2.32989618316274,    0, 0.664948091581372],
[  0,   0,                 0, -1.0,                 0],
[  0,   0, 0.914948091581372,    0,  -0.8014663450262]])

In [92]:
for i in [2]:
    P_calc[i] = P_calc[i] - P_calc[4] * P_calc[i,2] / P_calc[4,2]
P_calc[4] /= P_calc[4,2]
Matrix(P_calc)

Matrix([
[1.0,   0, -1.0,    0,                  0],
[  0,   0,    0,    0,                  0],
[  0, 1.0,    0,    0,  -1.37596919694205],
[  0,   0,    0, -1.0,                  0],
[  0,   0,  1.0,    0, -0.875969196942055]])

In [48]:
2 - 3 * P1 - 2 * P2

0.19003745745894696

In [58]:
P_real

array([[0.36477068, 0.25      , 0.05275528, 0.        , 0.16623702],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.05275528, 0.25      , 0.36477068, 0.        , 0.16623702],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.16623702, 0.25      , 0.16623702, 0.        , 0.36477068]])

In [62]:
D, P = np.linalg.eig(P_real)

In [63]:
Matrix(D)

Matrix([
[0.627718126787864],
[0.312015401528973],
[0.154578505290593],
[              1.0],
[                0]])

In [64]:
D_inf = np.array([0,0,0,1,0])

In [65]:
Matrix(P)

Matrix([
[-0.527138606242386,    -0.707106781186547,  0.471301272869949, 0.416282545466032,   0],
[                 0,                     0,                  0, 0.653895093326874,   0],
[-0.527138606242386,     0.707106781186548,   0.47130127286995, 0.416282545466032,   0],
[                 0,                     0,                  0,                 0, 1.0],
[-0.666520652056385, -3.32627339492276e-16, -0.745486566198433, 0.475225095721681,   0]])

In [93]:
P @ np.diag(D) @ P_inv

array([[0.36477068, 0.25      , 0.05275528, 0.        , 0.16623702],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.05275528, 0.25      , 0.36477068, 0.        , 0.16623702],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.16623702, 0.25      , 0.16623702, 0.        , 0.36477068]])

In [67]:
P_inv = np.linalg.inv(P)

In [94]:
P @ np.diag(D_inf) @ P_inv

array([[0.        , 0.63661977, 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.63661977, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.72676046, 0.        , 0.        , 0.        ]])

# Моделирование

In [54]:
from numba import njit
from time import time

@njit
def experiment(phi, R, N):
    x = np.array([round(R * np.cos(phi)), round(R * np.sin(phi))], dtype=np.int_)
    neig = np.zeros(9, dtype=np.short)
    steps = np.array([[1,0],[-1,0],[0,1],[0,-1]], dtype=np.int_)
    k = 0
    while True:
        walk_directions = np.random.randint(0,4, size=N)
        for i in range(1,N):
            x = x + steps[walk_directions[i]]
            if (np.abs(x) <= 1).all():
                if (x == 0).all():
                    return neig[1] + neig[3] + neig[5] + neig[7], k
                else:
                    neig[4 + 3 * x[1] + x[0]] = 1
        k += N
        if k > 1e6:
            return 0, 0
        
@njit            
def complex_experiment(R, N, Ni):
    res_log = np.zeros(6, dtype=np.int_)
    for i in range(Ni):
        phi = 2 * np.pi * np.random.rand()
        res = experiment(phi, R, N)
        res_log[res[0]] += 1
    res_log[5] = Ni
    return res_log

In [74]:
def write_out(res, R):
    res_float = np.array([R, 0, 0, 0, 0, 0, res[-1]], dtype=np.float_)
    res_float[1:-1] = res[:-1] / res[-1]
    np.savetxt('Spitser_R_' + str(R) + '.txt', 
               [res_float], 
               delimiter=' ', 
               fmt=['%d', '%1.6f', '%1.6f', '%1.6f', '%1.6f', '%1.6f','%d'], 
               newline=' ', 
               header=' R  pError  p_N1  p_N2  p_N3  p_N4  steps\n',
               comments='')

def main_func(R, Nmem, Ntime):
    result_log = np.zeros(6, dtype=np.ulonglong)
    k = 0
    while True:
        result_log = result_log + complex_experiment(R, Nmem, Ntime)
        write_out(result_log, R)

In [75]:
main_func(10, 100000, 100)

0

In [33]:
%time experiment(0,100, int(1e5))

CPU times: total: 406 ms
Wall time: 409 ms


(0, 0)

# Умное моделирование)

In [65]:
from numba import njit, jit, prange

@jit(parallel=True)
def create_walk():
    Pb = np.array([
        [0.36477068, 0.05275528, 0.16623702, 0.16623702, 0.25      ],
        [0.05275528, 0.36477068, 0.16623702, 0.16623702, 0.25      ],
        [0.16623702, 0.16623702, 0.36477068, 0.05275528, 0.25      ],
        [0.16623702, 0.16623702, 0.05275528, 0.36477068, 0.25      ],
        [0      , 0        , 0      , 0      , 1.      ]], dtype=np.float_)
    Xs = np.zeros(100, dtype=np.uint8)
    Xs[0] = np.random.choice(4)
    X_end = 0
    for i in range(1,100):
        Xs[i] = np.random.choice(5, None, True, Pb[Xs[i-1]])
        if Xs[i] == 4:
            return Xs[:i]
    return Xs

@njit
def linear_unique(X):
    count = np.zeros(4, dtype=np.uint8)
    for i in range(X.shape[0]):
        count[X[i]] += 1
    return (count > 0).sum()
        

@jit
def experiment():
    Xs = create_walk()
    return linear_unique(Xs)

@jit            
def complex_experiment(Ni):
    res_log = np.zeros(5, dtype=np.int_)
    for i in range(Ni):
        res = experiment()
        res_log[res - 1] += 1
    res_log[4] = Ni
    return res_log

def write_out(res):
    res_float = np.array([0, 0, 0, 0, res[-1]], dtype=np.float64)
    res_float[:-1] = res[:-1] / res[-1]
    np.savetxt('Spitser_simpler.txt', 
               [res_float], 
               delimiter=' ', 
               fmt=['%1.6f', '%1.6f', '%1.6f', '%1.6f','%d'], 
               newline=' ', 
               header='p_N1  p_N2  p_N3  p_N4  steps\n',
               comments='')

def main_func(Ni, Nstop):
    result_log = np.zeros(5, dtype=np.ulonglong)
    k = 0
    while k < Nstop:
        result_log = result_log + complex_experiment(Ni)
        write_out(result_log)
        k += 1

In [68]:
main_func(100, 1000)